# Generated by developer-kit/generate_managed_contract.py; do not edit.
module ADAIManagedContract
 GEOMETRY_PHASES = ["massing", "roof_profile", "archetypes", "primary_corrections", "facade_detail"].freeze
end
