#!/usr/bin/env python3
"""Compile a validated trace_manifest.json into a safe SketchUp Ruby scaffold.

This generator intentionally creates source-aligned placeholder solids. It does
not claim to create final openings, furniture semantics, or visual design.
Pass the generated .rb to sketchup_project_step inside a managed CAD project.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import re
import sys
import tempfile
from pathlib import Path
from typing import Any


def load_trace_validator(script_dir: Path) -> Any:
    validator_path = script_dir / "validate_trace.py"
    spec = importlib.util.spec_from_file_location("sketchup_trace_validator", validator_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load validator: {validator_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def ruby_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def ruby_number(value: Any, field: str) -> float:
    try:
        number = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{field} must be numeric") from exc
    if not number == number or number in (float("inf"), float("-inf")):
        raise ValueError(f"{field} must be finite")
    return number


def safe_name(value: str, fallback: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_\-]+", "_", value.strip())
    return (cleaned.strip("_") or fallback)[:80]


def default_height_mm(kind: str) -> float:
    if kind == "wall":
        return 2800.0
    if kind in {"door", "opening"}:
        return 2100.0
    if kind == "window":
        return 1500.0
    if kind in {"bed", "sofa", "chair", "dining_chair", "stool", "ottoman"}:
        return 650.0
    if kind in {"table", "desk", "coffee_table", "dining_table", "counter"}:
        return 750.0
    return 1000.0


def mapping_to_ruby(mapping: dict[str, Any], index: int) -> str:
    name = str(mapping.get("su_name") or f"trace_{index + 1}")
    kind = str(mapping.get("su_kind") or "trace_only")
    center = mapping.get("center_xy")
    footprint = mapping.get("footprint_wh")
    if not isinstance(center, list) or len(center) != 2:
        raise ValueError(f"{name}: center_xy must be [x, y]")
    if not isinstance(footprint, list) or len(footprint) != 2:
        raise ValueError(f"{name}: footprint_wh must be [width, depth]")
    cx, cy = (ruby_number(center[0], f"{name}.center_xy[0]"), ruby_number(center[1], f"{name}.center_xy[1]"))
    width, depth = (ruby_number(footprint[0], f"{name}.footprint_wh[0]"), ruby_number(footprint[1], f"{name}.footprint_wh[1]"))
    if width <= 0 or depth <= 0:
        raise ValueError(f"{name}: footprint dimensions must be positive")
    rotation = ruby_number(mapping.get("rotation_deg", 0.0), f"{name}.rotation_deg")
    height = ruby_number(mapping.get("height_mm", default_height_mm(kind)), f"{name}.height_mm")
    if height <= 0:
        raise ValueError(f"{name}: height_mm must be positive")
    source_handle = mapping.get("source_handle")
    source_layer = str(mapping.get("source_layer") or "")
    confidence = str(mapping.get("confidence") or "")
    return "\n".join(
        [
            f"    item = ai_trace_box(entities, [{cx:.6f}, {cy:.6f}], {width:.6f}, {depth:.6f}, {height:.6f}, {rotation:.6f}, {ruby_string(name)})",
            f"    item.set_attribute('ai_meta', 'source_handle', {ruby_string('' if source_handle is None else str(source_handle))})",
            f"    item.set_attribute('ai_meta', 'source_layer', {ruby_string(source_layer)})",
            f"    item.set_attribute('ai_meta', 'source_kind', {ruby_string(kind)})",
            f"    item.set_attribute('ai_meta', 'confidence', {ruby_string(confidence)})",
            "    made << item",
        ]
    )


def generate_ruby(manifest: dict[str, Any], project_id: str) -> str:
    meta = manifest.get("meta") or {}
    title = str(meta.get("title") or "Trace scaffold")
    items = manifest.get("mappings") or []
    rows = [mapping_to_ruby(item, index) for index, item in enumerate(items) if isinstance(item, dict)]
    if not rows:
        raise ValueError("Manifest has no valid mapping objects to compile")
    escaped_project = ruby_string(project_id)
    return f'''# Generated by build_from_trace_manifest.py. Inspect before managed execution.
# Source-aligned scaffold only: placeholders are not final walls/openings/furniture.
require 'sketchup.rb'

module PipClawManagedBuild
  extend self

  def ai_trace_box(entities, center_xy, width, depth, height, rotation_deg, name)
    raise "#{{name}}: non-positive size" if width <= 0 || depth <= 0 || height <= 0
    group = entities.add_group
    face = group.entities.add_face([
      Geom::Point3d.new((-width / 2.0).mm, (-depth / 2.0).mm, 0),
      Geom::Point3d.new(( width / 2.0).mm, (-depth / 2.0).mm, 0),
      Geom::Point3d.new(( width / 2.0).mm, ( depth / 2.0).mm, 0),
      Geom::Point3d.new((-width / 2.0).mm, ( depth / 2.0).mm, 0)
    ])
    raise "#{{name}}: face creation failed" unless face
    face.reverse! if face.normal.z < 0
    face.pushpull(height.mm)
    group.name = "Trace_#{{name}}"
    group.transform!(
      Geom::Transformation.translation(Geom::Vector3d.new(center_xy[0].mm, center_xy[1].mm, 0)) *
      Geom::Transformation.rotation(ORIGIN, Z_AXIS, rotation_deg.degrees)
    )
    raise "#{{name}}: scaffold solid failed" unless group.manifold?
    group
  end

  def build(entities, context)
    expected_project_id = {escaped_project}
    raise 'Managed project mismatch' unless context['project_id'].to_s == expected_project_id
    phase_group = context['phase_group']
    phase_group.set_attribute('ai_meta', 'title', {ruby_string(title)})
    phase_group.set_attribute('ai_meta', 'generated_by', 'build_from_trace_manifest.py')
    phase_group.set_attribute('ai_meta', 'source_role', 'trace_scaffold')
    made = []
{chr(10).join(rows)}
    {{
      'created' => made.length,
      'project_id' => expected_project_id,
      'note' => 'Source-aligned placeholder scaffold only.'
    }}
  end
end
'''


def validate_manifest(manifest_path: Path, validator: Any) -> dict[str, Any]:
    try:
        data = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
    except FileNotFoundError as exc:
        raise ValueError(f"Manifest does not exist: {manifest_path}") from exc
    except json.JSONDecodeError as exc:
        raise ValueError(f"Manifest JSON is invalid: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError("Manifest root must be an object")
    report = validator.Report()
    validator.check_schema(data, report)
    validator.check_source_layers(data, report)
    validator.check_mappings(data, report)
    validator.check_coverage(data, report)
    validator.check_additions(data, report)
    result = {"ok": report.ok, "errors": report.errors, "warnings": report.warns, "manifest": data}
    if not result["ok"]:
        messages = "; ".join(f"{item['code']}: {item['message']}" for item in report.errors)
        raise ValueError(f"Trace validation failed: {messages}")
    return result


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def self_test(script_dir: Path) -> int:
    validator = load_trace_validator(script_dir)
    with tempfile.TemporaryDirectory() as temporary:
        root = Path(temporary)
        manifest_path = root / "trace_manifest.json"
        output_path = root / "generated.rb"
        valid = {
            "meta": {"title": "test", "source": "synthetic"},
            "source_layers": [{"name": "A-WALL", "status": "mapped", "entity_count": 1}],
            "mappings": [{"su_name": "south_wall", "su_kind": "wall", "source_layer": "A-WALL", "confidence": "explicit", "center_xy": [2000, 0], "footprint_wh": [4000, 240], "rotation_deg": 0}],
        }
        write_text(manifest_path, json.dumps(valid, ensure_ascii=False))
        validated = validate_manifest(manifest_path, validator)
        write_text(output_path, generate_ruby(validated["manifest"], "selftest"))
        text = output_path.read_text(encoding="utf-8")
        if (
            "module PipClawManagedBuild" not in text
            or "def build(entities, context)" not in text
            or "ai_trace_box(entities" not in text
            or "south_wall" not in text
            or "source_layer" not in text
            or "start_operation" in text
            or "Sketchup.active_model" in text
        ):
            print("[FAIL] generated Ruby lacks required scaffold metadata")
            return 1
        invalid = dict(valid)
        invalid["mappings"] = []
        write_text(manifest_path, json.dumps(invalid))
        try:
            validate_manifest(manifest_path, validator)
        except ValueError:
            print("[OK] build_from_trace_manifest self-test passed")
            return 0
        print("[FAIL] invalid manifest was accepted")
        return 1


def main() -> int:
    parser = argparse.ArgumentParser(description="Compile a validated trace manifest into a SketchUp Ruby scaffold")
    parser.add_argument("--manifest", type=Path, help="Input trace_manifest.json")
    parser.add_argument("--output", type=Path, help="Generated Ruby path")
    parser.add_argument("--project-id", help="Stable project identifier for phase replacement")
    parser.add_argument("--self-test", action="store_true", help="Run local generator tests without SketchUp")
    arguments = parser.parse_args()
    script_dir = Path(__file__).resolve().parent
    if arguments.self_test:
        return self_test(script_dir)
    if not arguments.manifest or not arguments.output or not arguments.project_id:
        parser.error("--manifest, --output, and --project-id are required unless --self-test is used")
    try:
        validator = load_trace_validator(script_dir)
        validated = validate_manifest(arguments.manifest, validator)
        ruby = generate_ruby(validated["manifest"], arguments.project_id)
        write_text(arguments.output, ruby)
    except (OSError, RuntimeError, ValueError) as exc:
        print(f"[FAIL] {exc}", file=sys.stderr)
        return 1
    print(json.dumps({"ok": True, "output": str(arguments.output), "project_id": arguments.project_id, "warnings": validated["warnings"], "note": "Generated managed source-aligned scaffold; pass this file to sketchup_project_step."}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())

